export function dashboardHtml(simulationEnabled: boolean): string {
  const mode = simulationEnabled ? 'SIMULATOR ON' : 'MONITOR ONLY'
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>CodingMacro</title>
  <style>
    :root{color-scheme:light;--bg:#f3f3f0;--surface:#fafaf8;--line:#d8d8d3;--line-hi:#b8b9b7;--text:#17181a;--muted:#6e7176;--dim:#9b9da1;--core:#191a1e;--core-2:#282a30;--light:#b9d8ff}
    *{box-sizing:border-box}html{background:var(--bg)}body{margin:0;color:var(--text);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;min-height:100vh;background:radial-gradient(ellipse 60% 30% at 50% 0,#fdfdfb 0,var(--bg) 72%);letter-spacing:-.01em}
    main{position:relative;width:min(1160px,94vw);margin:auto;padding:30px 0 64px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:22px}.brand{display:flex;align-items:center;gap:15px}.mark{width:48px;height:48px;border:1px solid #c9cac7;border-radius:15px;background:linear-gradient(145deg,#fbfbf9,#e3e3df);box-shadow:inset 0 1px #ffffff,0 12px 26px #23232312;display:grid;place-items:center;color:var(--text);font:750 15px/1 ui-sans-serif,system-ui;letter-spacing:-.08em}.brand h1{margin:0;font:680 clamp(25px,4vw,37px)/1 ui-sans-serif,system-ui;letter-spacing:-.045em}.brand p{margin:7px 0 0;color:var(--muted);font-size:12px}.pill{position:relative;border:1px solid #d2d3d0;background:#fafaf8;border-radius:12px;padding:9px 13px 9px 31px;color:#4e5156;white-space:nowrap;font-size:11px;letter-spacing:.08em;box-shadow:0 8px 22px #2525250a}.pill:before{content:"";position:absolute;left:13px;top:50%;width:7px;height:7px;border-radius:50%;background:#526b89;transform:translateY(-50%);box-shadow:0 0 11px #8cbfff}
    .grid{display:grid;grid-template-columns:minmax(0,1.62fr) minmax(280px,.58fr);gap:16px}.card{border:1px solid var(--line);background:var(--surface);border-radius:20px;padding:18px;box-shadow:inset 0 1px #ffffff,0 24px 60px #2e2e2e0b}.card h2{font:620 11px/1 ui-sans-serif,system-ui;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);margin:1px 0 17px}
    .pad{position:relative;min-height:520px;padding:0}.shell{position:absolute;z-index:0;left:9%;right:9%;top:54px;height:268px;border:1px solid #d0d1ce;border-radius:42% 42% 28% 28% / 30% 30% 44% 44%;background:linear-gradient(150deg,#ffffff 0,#efefec 54%,#d6d7d4 100%);box-shadow:inset 0 1px #ffffff,0 25px 30px #2525251c}.shell:before,.shell:after{content:"";position:absolute;z-index:-1;top:155px;width:176px;height:265px;border:1px solid #d0d1ce;background:linear-gradient(155deg,#f8f8f5,#d9dad6);box-shadow:inset 0 1px #ffffff,0 20px 24px #25252514}.shell:before{left:1%;border-radius:42% 28% 58% 48%;transform:rotate(14deg)}.shell:after{right:1%;border-radius:28% 42% 48% 58%;transform:rotate(-14deg)}.core{position:absolute;z-index:1;left:31%;right:31%;top:83px;height:296px;border-radius:28% 28% 48% 48% / 18% 18% 36% 36%;background:linear-gradient(155deg,var(--core-2),#111216);box-shadow:inset 0 1px #ffffff24,0 8px 20px #11121629}.shoulders{position:absolute;z-index:3;left:10%;right:10%;top:44px;display:flex;justify-content:space-between}.shoulders div{display:flex;gap:8px}.control{appearance:none;position:relative;z-index:3;border:1px solid #3d4047;background:linear-gradient(155deg,#292b31,#141519);color:#eceef2;border-radius:12px;min-width:54px;min-height:44px;padding:9px 12px;font:650 12px ui-monospace,monospace;cursor:pointer;box-shadow:inset 0 1px #ffffff24,0 4px 0 #0a0b0d;transition:transform .12s cubic-bezier(.2,.8,.2,1),background .12s,border-color .12s,box-shadow .12s,color .12s}.control:hover{border-color:#777b84}.control:active,.control.active{transform:translateY(3px) scale(.98);color:#101116;background:#f4f6fa;border-color:#ffffff;box-shadow:inset 0 1px #ffffff,0 0 25px #78b8ff,0 1px 0 #0a0b0d}.control[data-monitor="true"]{cursor:default}.face,.dpad{position:absolute;z-index:3;top:160px;width:142px;height:142px}.dpad{left:10%}.face{right:10%}.face .control,.dpad .control{position:absolute;width:46px;height:46px;min-width:46px;border-radius:50%;font-size:16px}.up{left:48px;top:0}.down{left:48px;bottom:0}.left{left:0;top:48px}.right{right:0;top:48px}.a{left:48px;bottom:0}.b{right:0;top:48px}.x{left:0;top:48px}.y{left:48px;top:0}
    .sticks{position:absolute;z-index:3;inset:0}.stickrow{display:contents}.sticks [data-button="touchpad"]{position:absolute;left:50%;top:101px;transform:translateX(-50%);width:142px;height:74px;border-radius:10px;color:#bfc2c8;background:linear-gradient(155deg,#26282d,#15161a);box-shadow:inset 0 1px #ffffff21,0 3px 0 #090a0c}.sticks [data-button="l3"],.sticks [data-button="r3"]{position:absolute;top:285px;width:62px;height:62px;border-radius:50%;box-shadow:inset 0 1px #ffffff20,inset 0 0 0 8px #202228,0 4px 0 #090a0c}.sticks [data-button="l3"]{left:37%}.sticks [data-button="r3"]{right:37%}.stickrow:nth-child(2){position:absolute;display:flex;left:50%;top:365px;transform:translateX(-50%);gap:9px}.workflow{position:absolute;z-index:3;left:50%;bottom:4px;transform:translateX(-50%);display:grid;grid-template-columns:repeat(4,1fr);gap:8px;width:84%}.workflow .control{font-size:10px;letter-spacing:.06em;padding:8px;min-width:0;color:#34363a;background:#f2f2ef;border-color:#c8c9c6;box-shadow:inset 0 1px #ffffff,0 3px 0 #b8b9b6}.hint{position:absolute;z-index:4;left:50%;top:181px;transform:translateX(-50%);color:#858991;font-size:9px;letter-spacing:.08em;white-space:nowrap}
    .status{display:grid}.metric{padding:14px 2px 16px;border-bottom:1px solid var(--line)}.metric:first-child{padding-top:3px}.metric label{display:block;color:var(--dim);font-size:10px;text-transform:uppercase;letter-spacing:.13em}.metric strong{display:block;margin-top:6px;color:var(--text);font:620 16px ui-sans-serif,system-ui;letter-spacing:-.02em}.sessions{display:grid;gap:7px;margin-top:9px}.session{display:flex;align-items:center;gap:10px;border:1px solid var(--line);border-radius:10px;padding:9px;background:#f5f5f2}.dot{width:7px;height:7px;border-radius:50%;background:#a5a7aa}.dot.executing,.dot.waiting{background:#526b89;box-shadow:0 0 10px #8cbfff}.dot.complete{background:#71747a}.dot.error{background:#414349}.empty{color:var(--dim);padding:5px 0}.legend{margin-top:15px;color:var(--dim);font-size:11px;line-height:1.7}.notice{margin:17px 0 0;border-left:1px solid #a7a9ad;padding-left:12px;color:var(--muted);font-size:11px;line-height:1.7}
    .profile{margin-top:16px}.profile summary{cursor:pointer;font:620 13px ui-sans-serif,system-ui}.profile textarea{width:100%;min-height:320px;margin-top:16px;padding:14px;border:1px solid var(--line);border-radius:12px;background:#f5f5f2;color:var(--text);font:12px/1.55 ui-monospace,monospace;resize:vertical}.profile textarea:focus{outline:1px solid #37393d;outline-offset:2px}.toolbar{display:flex;flex-wrap:wrap;gap:9px;margin-top:10px;align-items:center}.toolbar .control{min-height:38px}.saveState{color:var(--muted);font-size:11px}.control:focus-visible{outline:2px solid #33353a;outline-offset:3px}
    @media(max-width:820px){main{width:min(94vw,650px);padding-top:22px}.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.pad{min-height:470px}.shell{left:4px;right:4px}.dpad{left:5%}.face{right:5%}.sticks [data-button="l3"]{left:34%}.sticks [data-button="r3"]{right:34%}.workflow{width:94%}}@media(prefers-reduced-motion:reduce){.control{transition:none}}
  </style>
</head>
<body><main>
  <header class="top"><div class="brand"><div class="mark">CM</div><div><h1>CodingMacro</h1><p>Gamepad control for AI coding agents.</p></div></div><div class="pill" id="mode">${mode}</div></header>
  <section class="grid">
    <div class="card"><h2>Controller</h2><div class="pad"><div class="shell" aria-hidden="true"></div><div class="core" aria-hidden="true"></div>
      <div class="shoulders"><div><button class="control" data-button="l2" data-xbox="LT" data-playstation="L2">LT</button><button class="control" data-button="l1" data-xbox="LB" data-playstation="L1">LB</button></div><div><button class="control" data-button="r1" data-xbox="RB" data-playstation="R1">RB</button><button class="control" data-button="r2" data-xbox="RT" data-playstation="R2">RT</button></div></div>
      <div class="hint">mouse / touch / keyboard shortcuts</div>
      <div class="dpad"><button class="control up" data-button="dpad_up">↑</button><button class="control down" data-button="dpad_down">↓</button><button class="control left" data-button="dpad_left">←</button><button class="control right" data-button="dpad_right">→</button></div>
      <div class="face"><button class="control a" data-button="south" data-xbox="A" data-playstation="×">A</button><button class="control b" data-button="east" data-xbox="B" data-playstation="○">B</button><button class="control x" data-button="west" data-xbox="X" data-playstation="□">X</button><button class="control y" data-button="north" data-xbox="Y" data-playstation="△">Y</button></div>
      <div class="sticks"><div class="stickrow"><button class="control" data-button="l3">L3</button><button class="control" data-button="touchpad" data-xbox="AGENT" data-playstation="TOUCHPAD">AGENT</button><button class="control" data-button="r3">R3</button></div><div class="stickrow"><button class="control" data-gesture="rstick_ccw">EFF−</button><button class="control" data-gesture="rstick_cw">EFF+</button></div></div>
      <div class="workflow"><button class="control" data-gesture="lstick_up">REVIEW</button><button class="control" data-gesture="lstick_down">DEBUG</button><button class="control" data-gesture="lstick_left">REFACTOR</button><button class="control" data-gesture="lstick_right">TESTS</button></div>
    </div></div>
    <aside class="card"><h2>Agent HUD</h2><div class="status">
      <div class="metric"><label>Connection</label><strong id="connection">connecting…</strong></div>
      <div class="metric"><label>Agent state</label><strong id="agentState">idle</strong></div>
      <div class="metric"><label>Sessions</label><div class="sessions" id="sessions"><div class="empty">No tracked sessions</div></div></div>
      <p class="notice" id="notice" data-prefix="${simulationEnabled ? 'Simulator injects normalized controller events. Real HID parsing stays untouched.' : 'Run with --simulate to enable virtual controls.'}">${simulationEnabled ? 'Simulator injects normalized controller events. Real HID parsing stays untouched.' : 'Run with --simulate to enable virtual controls.'} Hold A for 500ms when an agent is waiting for approval.</p>
    </div><div class="legend" id="legend">Keys: A/B/X/Y · arrows · Q/E bumpers · Z/C triggers · H agent · I/J/K/L workflows · U/O effort</div></aside>
  </section>
  <details class="card profile"><summary>Controller profile · import, edit, export</summary><textarea id="profile" spellcheck="false" aria-label="CodingMacro controller profile"></textarea><div class="toolbar"><button class="control" id="saveProfile">SAVE PROFILE</button><button class="control" id="downloadProfile">EXPORT JSON</button><button class="control" id="importProfile">IMPORT JSON</button><input id="profileFile" type="file" accept="application/json,.json" hidden><span class="saveState" id="saveState">Changes apply after restart.</span></div></details>
</main>
<script>
const enabled=${simulationEnabled ? 'true' : 'false'};
const post=e=>enabled&&fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(e)});
const button=(id,pressed)=>post({kind:'button',button:id,pressed});
const gesture=id=>{const [stick,dir]=id.split('_');if(dir==='cw'||dir==='ccw'){const seq=dir==='cw'?[[1,0],[0,1],[-1,0],[0,-1],[0,0]]:[[1,0],[0,-1],[-1,0],[0,1],[0,0]];seq.forEach(([x,y],i)=>setTimeout(()=>{post({kind:'axis',axis:stick==='rstick'?'right_x':'left_x',value:x});post({kind:'axis',axis:stick==='rstick'?'right_y':'left_y',value:y})},i*28));return}const map={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},[x,y]=map[dir];post({kind:'axis',axis:stick==='rstick'?'right_x':'left_x',value:x});post({kind:'axis',axis:stick==='rstick'?'right_y':'left_y',value:y});setTimeout(()=>{post({kind:'axis',axis:stick==='rstick'?'right_x':'left_x',value:0});post({kind:'axis',axis:stick==='rstick'?'right_y':'left_y',value:0})},90)};
document.querySelectorAll('[data-button]').forEach(el=>{if(!enabled){el.dataset.monitor='true';return}const id=el.dataset.button;const down=e=>{e.preventDefault();el.classList.add('active');button(id,true)},up=e=>{e.preventDefault();el.classList.remove('active');button(id,false)};el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('pointerleave',e=>{if(el.classList.contains('active'))up(e)})});
document.querySelectorAll('[data-gesture]').forEach(el=>{if(!enabled){el.dataset.monitor='true';return}el.onclick=()=>gesture(el.dataset.gesture)});
const keys={a:'south',b:'east',x:'west',y:'north',ArrowUp:'dpad_up',ArrowDown:'dpad_down',ArrowLeft:'dpad_left',ArrowRight:'dpad_right',q:'l1',e:'r1',z:'l2',c:'r2',h:'touchpad'};const gestures={i:'lstick_up',k:'lstick_down',j:'lstick_left',l:'lstick_right',u:'rstick_ccw',o:'rstick_cw'};addEventListener('keydown',e=>{if(e.repeat)return;if(keys[e.key]){e.preventDefault();button(keys[e.key],true)}else if(gestures[e.key])gesture(gestures[e.key])});addEventListener('keyup',e=>{if(keys[e.key]){e.preventDefault();button(keys[e.key],false)}});
const colors={executing:'executing',waiting:'waiting',complete:'complete',error:'error',idle:''};let shownController='',shownEventSeq=0;const flashTimers=new WeakMap;function showController(type){if(type===shownController)return;shownController=type;const playstation=type==='dualsense'||type==='ds4';document.querySelectorAll('[data-playstation]').forEach(el=>el.textContent=playstation?el.dataset.playstation:el.dataset.xbox);notice.textContent=notice.dataset.prefix+' Hold '+(playstation?'×':'A')+' for 500ms when an agent is waiting for approval.';legend.textContent=playstation?'PS5: ×/○/□/△ · L1/L2/R1/R2 · touchpad · sticks':'Keys: A/B/X/Y · arrows · Q/E bumpers · Z/C triggers · H agent · I/J/K/L workflows · U/O effort'}function showEvents(events){for(const event of events||[]){if(!event.seq||event.seq<=shownEventSeq)continue;shownEventSeq=event.seq;if(event.kind!=='button'||!event.pressed)continue;const el=document.querySelector('[data-button="'+event.button+'"]');if(!el)continue;el.classList.add('active');clearTimeout(flashTimers.get(el));flashTimers.set(el,setTimeout(()=>el.classList.remove('active'),210))}}async function refresh(){try{const r=await fetch('/api/status'),s=await r.json();showController(s.controllerType||'');showEvents(s.recentControllerEvents||(s.lastControllerEvent?[s.lastControllerEvent]:[]));connection.textContent='localhost · '+(s.controllerType||'waiting for HID')+(s.simulation?' + simulated':'');agentState.textContent=s.aggregate.focusIsAttention?'needs attention':s.aggregate.playing?'executing':'idle';sessions.innerHTML=s.sessions.length?s.sessions.map(x=>'<div class="session"><span class="dot '+colors[x.state]+'"></span><span>'+x.id.slice(0,14)+'</span><small style="margin-left:auto;color:var(--muted)">'+x.state+'</small></div>').join(''):'<div class="empty">No tracked sessions</div>'}catch{connection.textContent='disconnected'}}refresh();setInterval(refresh,120);
const profileEditor=document.getElementById('profile'),profileState=document.getElementById('saveState'),profileFileInput=document.getElementById('profileFile');async function loadProfile(){const r=await fetch('/api/config');if(r.ok)profileEditor.value=JSON.stringify(await r.json(),null,2);else profileState.textContent='Profile unavailable on this client.'}loadProfile();document.getElementById('saveProfile').onclick=async()=>{try{const value=JSON.parse(profileEditor.value),r=await fetch('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});if(!r.ok)throw new Error((await r.json()).error||'save failed');profileState.textContent='Saved. Restart CodingMacro to apply.'}catch(e){profileState.textContent='Invalid profile: '+e.message}};document.getElementById('downloadProfile').onclick=()=>{const blob=new Blob([profileEditor.value+'\\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='codingmacro-profile.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('importProfile').onclick=()=>profileFileInput.click();profileFileInput.onchange=async()=>{const file=profileFileInput.files[0];if(!file)return;profileEditor.value=JSON.stringify(JSON.parse(await file.text()),null,2);profileState.textContent='Imported locally. Press SAVE PROFILE.'};
</script></body></html>`
}
