export function dashboardHtml(simulationEnabled: boolean): string {
  const mode = simulationEnabled ? 'SIMULATOR ON' : 'MONITOR ONLY'
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>CodingMacro</title>
  <style>
    :root{color-scheme:dark;--ink:#17130f;--panel:#231d17;--line:#493b2f;--paper:#f4eadb;--muted:#b9aa98;--ember:#ff6b2c;--gold:#f7b84b;--green:#5dcc8b;--red:#ff6b69;--blue:#67a8ff}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -20%,#49301e 0,var(--ink) 45%);color:var(--paper);font:15px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;min-height:100vh}
    main{width:min(1080px,94vw);margin:auto;padding:32px 0 60px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}.brand{display:flex;align-items:center;gap:14px}.mark{width:46px;height:46px;border-radius:14px;background:linear-gradient(145deg,var(--gold),var(--ember));box-shadow:0 10px 30px #ff6b2c33;display:grid;place-items:center;color:#25170c;font-weight:900;font-size:20px}.brand h1{margin:0;font:700 clamp(24px,4vw,38px)/1 ui-sans-serif,system-ui}.brand p{margin:6px 0 0;color:var(--muted)}.pill{border:1px solid var(--line);background:#16110dcc;border-radius:99px;padding:8px 12px;color:var(--gold);white-space:nowrap}
    .grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:18px}.card{border:1px solid var(--line);background:linear-gradient(150deg,#2a211acc,#1c1713e6);border-radius:24px;padding:20px;box-shadow:0 18px 60px #0006;backdrop-filter:blur(14px)}.card h2{font:650 13px/1 ui-sans-serif,system-ui;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin:0 0 18px}
    .pad{position:relative;min-height:480px;border-radius:38% 38% 28% 28%;background:linear-gradient(160deg,#3b3027,#17130f);border:1px solid #5a4939;box-shadow:inset 0 1px #ffffff19,0 30px 80px #0008;padding:26px}.shoulders{display:flex;justify-content:space-between}.shoulders div{display:flex;gap:8px}.control{appearance:none;border:1px solid #655240;background:#211a15;color:var(--paper);border-radius:14px;min-width:54px;min-height:44px;padding:9px 12px;font:700 13px ui-monospace,monospace;cursor:pointer;box-shadow:inset 0 1px #ffffff14,0 5px 0 #0b0907;transition:.08s transform,.08s background}.control:hover{border-color:var(--gold)}.control:active,.control.active{transform:translateY(4px);box-shadow:inset 0 1px #ffffff14,0 1px 0 #0b0907;background:#4a2b1b;border-color:var(--ember)}.control[disabled]{opacity:.35;cursor:not-allowed}.face,.dpad{position:absolute;top:150px;width:154px;height:154px}.dpad{left:54px}.face{right:54px}.face .control,.dpad .control{position:absolute;width:48px;height:48px;min-width:48px;border-radius:50%}.up{left:53px;top:0}.down{left:53px;bottom:0}.left{left:0;top:53px}.right{right:0;top:53px}.a{right:0;top:53px;color:var(--green)}.b{left:53px;bottom:0;color:var(--red)}.x{left:0;top:53px;color:var(--blue)}.y{left:53px;top:0;color:var(--gold)}
    .sticks{position:absolute;left:50%;top:164px;transform:translateX(-50%);display:grid;gap:18px}.stickrow{display:flex;gap:10px;justify-content:center}.stickrow .control{min-width:42px}.workflow{position:absolute;left:50%;bottom:28px;transform:translateX(-50%);display:grid;grid-template-columns:repeat(4,1fr);gap:8px;width:calc(100% - 56px)}.workflow .control{font-size:11px;padding:8px;min-width:0}.hint{position:absolute;left:50%;top:124px;transform:translateX(-50%);color:#8f7e6b;font-size:11px;white-space:nowrap}
    .status{display:grid;gap:12px}.metric{border:1px solid #3f342b;background:#17120f;border-radius:16px;padding:14px}.metric label{display:block;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.1em}.metric strong{display:block;margin-top:5px;font:650 17px ui-sans-serif,system-ui}.sessions{display:grid;gap:8px}.session{display:flex;align-items:center;gap:10px;border:1px solid #3f342b;border-radius:13px;padding:10px}.dot{width:9px;height:9px;border-radius:50%;background:#777}.dot.executing{background:var(--blue);box-shadow:0 0 12px var(--blue)}.dot.waiting{background:var(--gold);box-shadow:0 0 12px var(--gold)}.dot.complete{background:var(--green)}.dot.error{background:var(--red)}.empty{color:var(--muted);padding:10px 0}.legend{margin-top:16px;color:var(--muted);font-size:12px}.notice{border-left:3px solid var(--ember);padding-left:12px;color:var(--muted)}
    .profile{margin-top:18px}.profile summary{cursor:pointer;font:650 14px ui-sans-serif,system-ui}.profile textarea{width:100%;min-height:320px;margin-top:16px;padding:14px;border:1px solid var(--line);border-radius:14px;background:#120f0c;color:var(--paper);font:12px/1.5 ui-monospace,monospace;resize:vertical}.profile textarea:focus{outline:2px solid var(--ember);outline-offset:2px}.toolbar{display:flex;flex-wrap:wrap;gap:9px;margin-top:10px;align-items:center}.toolbar .control{min-height:38px}.saveState{color:var(--muted);font-size:12px}.control:focus-visible{outline:2px solid var(--gold);outline-offset:3px}
    @media(max-width:820px){.grid{grid-template-columns:1fr}.pad{min-height:440px}.face{right:26px}.dpad{left:26px}.top{align-items:flex-start;flex-direction:column}}
  </style>
</head>
<body><main>
  <header class="top"><div class="brand"><div class="mark">CM</div><div><h1>CodingMacro</h1><p>Gamepad control for AI coding agents.</p></div></div><div class="pill" id="mode">${mode}</div></header>
  <section class="grid">
    <div class="card"><h2>Controller</h2><div class="pad">
      <div class="shoulders"><div><button class="control" data-button="l2">LT</button><button class="control" data-button="l1">LB</button></div><div><button class="control" data-button="r1">RB</button><button class="control" data-button="r2">RT</button></div></div>
      <div class="hint">mouse / touch / keyboard shortcuts</div>
      <div class="dpad"><button class="control up" data-button="dpad_up">↑</button><button class="control down" data-button="dpad_down">↓</button><button class="control left" data-button="dpad_left">←</button><button class="control right" data-button="dpad_right">→</button></div>
      <div class="face"><button class="control a" data-button="south">A</button><button class="control b" data-button="east">B</button><button class="control x" data-button="west">X</button><button class="control y" data-button="north">Y</button></div>
      <div class="sticks"><div class="stickrow"><button class="control" data-button="l3">L3</button><button class="control" data-button="touchpad">AGENT</button><button class="control" data-button="r3">R3</button></div><div class="stickrow"><button class="control" data-gesture="rstick_ccw">EFF−</button><button class="control" data-gesture="rstick_cw">EFF+</button></div></div>
      <div class="workflow"><button class="control" data-gesture="lstick_up">REVIEW</button><button class="control" data-gesture="lstick_down">DEBUG</button><button class="control" data-gesture="lstick_left">REFACTOR</button><button class="control" data-gesture="lstick_right">TESTS</button></div>
    </div></div>
    <aside class="card"><h2>Agent HUD</h2><div class="status">
      <div class="metric"><label>Connection</label><strong id="connection">connecting…</strong></div>
      <div class="metric"><label>Agent state</label><strong id="agentState">idle</strong></div>
      <div class="metric"><label>Sessions</label><div class="sessions" id="sessions"><div class="empty">No tracked sessions</div></div></div>
      <p class="notice" id="notice">${simulationEnabled ? 'Simulator injects normalized controller events. Real HID parsing stays untouched.' : 'Run with --simulate to enable virtual controls.'} Hold A for 500ms when an agent is waiting for approval.</p>
    </div><div class="legend">Keys: A/B/X/Y · arrows · Q/E bumpers · Z/C triggers · H agent · I/J/K/L workflows · U/O effort</div></aside>
  </section>
  <details class="card profile"><summary>Controller profile · import, edit, export</summary><textarea id="profile" spellcheck="false" aria-label="CodingMacro controller profile"></textarea><div class="toolbar"><button class="control" id="saveProfile">SAVE PROFILE</button><button class="control" id="downloadProfile">EXPORT JSON</button><button class="control" id="importProfile">IMPORT JSON</button><input id="profileFile" type="file" accept="application/json,.json" hidden><span class="saveState" id="saveState">Changes apply after restart.</span></div></details>
</main>
<script>
const enabled=${simulationEnabled ? 'true' : 'false'};
const post=e=>enabled&&fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(e)});
const button=(id,pressed)=>post({kind:'button',button:id,pressed});
const gesture=id=>{const [stick,dir]=id.split('_');if(dir==='cw'||dir==='ccw'){const seq=dir==='cw'?[[1,0],[0,1],[-1,0],[0,-1],[0,0]]:[[1,0],[0,-1],[-1,0],[0,1],[0,0]];seq.forEach(([x,y],i)=>setTimeout(()=>{post({kind:'axis',axis:stick==='rstick'?'right_x':'left_x',value:x});post({kind:'axis',axis:stick==='rstick'?'right_y':'left_y',value:y})},i*28));return}const map={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},[x,y]=map[dir];post({kind:'axis',axis:stick==='rstick'?'right_x':'left_x',value:x});post({kind:'axis',axis:stick==='rstick'?'right_y':'left_y',value:y});setTimeout(()=>{post({kind:'axis',axis:stick==='rstick'?'right_x':'left_x',value:0});post({kind:'axis',axis:stick==='rstick'?'right_y':'left_y',value:0})},90)};
document.querySelectorAll('[data-button]').forEach(el=>{if(!enabled)el.disabled=true;const id=el.dataset.button;const down=e=>{e.preventDefault();el.classList.add('active');button(id,true)},up=e=>{e.preventDefault();el.classList.remove('active');button(id,false)};el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('pointerleave',e=>{if(el.classList.contains('active'))up(e)})});
document.querySelectorAll('[data-gesture]').forEach(el=>{if(!enabled)el.disabled=true;el.onclick=()=>gesture(el.dataset.gesture)});
const keys={a:'south',b:'east',x:'west',y:'north',ArrowUp:'dpad_up',ArrowDown:'dpad_down',ArrowLeft:'dpad_left',ArrowRight:'dpad_right',q:'l1',e:'r1',z:'l2',c:'r2',h:'touchpad'};const gestures={i:'lstick_up',k:'lstick_down',j:'lstick_left',l:'lstick_right',u:'rstick_ccw',o:'rstick_cw'};addEventListener('keydown',e=>{if(e.repeat)return;if(keys[e.key]){e.preventDefault();button(keys[e.key],true)}else if(gestures[e.key])gesture(gestures[e.key])});addEventListener('keyup',e=>{if(keys[e.key]){e.preventDefault();button(keys[e.key],false)}});
const colors={executing:'executing',waiting:'waiting',complete:'complete',error:'error',idle:''};async function refresh(){try{const r=await fetch('/api/status'),s=await r.json();connection.textContent='localhost · '+(s.simulation?'simulated + HID':'HID');agentState.textContent=s.aggregate.focusIsAttention?'needs attention':s.aggregate.playing?'executing':'idle';sessions.innerHTML=s.sessions.length?s.sessions.map(x=>'<div class="session"><span class="dot '+colors[x.state]+'"></span><span>'+x.id.slice(0,14)+'</span><small style="margin-left:auto;color:var(--muted)">'+x.state+'</small></div>').join(''):'<div class="empty">No tracked sessions</div>'}catch{connection.textContent='disconnected'}}refresh();setInterval(refresh,700);
const profileEditor=document.getElementById('profile'),profileState=document.getElementById('saveState'),profileFileInput=document.getElementById('profileFile');async function loadProfile(){const r=await fetch('/api/config');if(r.ok)profileEditor.value=JSON.stringify(await r.json(),null,2);else profileState.textContent='Profile unavailable on this client.'}loadProfile();document.getElementById('saveProfile').onclick=async()=>{try{const value=JSON.parse(profileEditor.value),r=await fetch('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});if(!r.ok)throw new Error((await r.json()).error||'save failed');profileState.textContent='Saved. Restart CodingMacro to apply.'}catch(e){profileState.textContent='Invalid profile: '+e.message}};document.getElementById('downloadProfile').onclick=()=>{const blob=new Blob([profileEditor.value+'\\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='codingmacro-profile.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('importProfile').onclick=()=>profileFileInput.click();profileFileInput.onchange=async()=>{const file=profileFileInput.files[0];if(!file)return;profileEditor.value=JSON.stringify(JSON.parse(await file.text()),null,2);profileState.textContent='Imported locally. Press SAVE PROFILE.'};
</script></body></html>`
}
